name: bimonthly build latest
on: 
  schedule:
    - cron: "0 3 1,15 * *"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'latest'

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV #Fix https://github.community/t/repository-name-in-environment-variable/16856/6
        shell: bash

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: set lower case repository
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REPO_LC }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
          # always generate latest tag on push

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/${{ env.REPOSITORY_NAME }}:latest
            ${{ steps.meta.outputs.tags }}
